# Generated by Django 3.1 on 2020-08-26 16:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndDistricts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('gid_0', models.CharField(blank=True, max_length=80, null=True)),
                ('name_0', models.CharField(blank=True, max_length=80, null=True)),
                ('gid_1', models.CharField(blank=True, max_length=80, null=True)),
                ('name_1', models.CharField(blank=True, max_length=80, null=True)),
                ('nl_name_1', models.CharField(blank=True, max_length=80, null=True)),
                ('gid_2', models.CharField(blank=True, max_length=80, null=True)),
                ('name_2', models.CharField(blank=True, max_length=80, null=True)),
                ('varname_2', models.CharField(blank=True, max_length=80, null=True)),
                ('nl_name_2', models.CharField(blank=True, max_length=80, null=True)),
                ('type_2', models.CharField(blank=True, max_length=80, null=True)),
                ('engtype_2', models.CharField(blank=True, max_length=80, null=True)),
                ('cc_2', models.CharField(blank=True, max_length=80, null=True)),
                ('hasc_2', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'IND_DISTRICTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('gid_0', models.CharField(blank=True, max_length=80, null=True)),
                ('name_0', models.CharField(blank=True, max_length=80, null=True)),
                ('gid_1', models.CharField(blank=True, max_length=80, null=True)),
                ('name_1', models.CharField(blank=True, max_length=80, null=True)),
                ('varname_1', models.CharField(blank=True, max_length=100, null=True)),
                ('nl_name_1', models.CharField(blank=True, max_length=80, null=True)),
                ('type_1', models.CharField(blank=True, max_length=80, null=True)),
                ('engtype_1', models.CharField(blank=True, max_length=80, null=True)),
                ('cc_1', models.CharField(blank=True, max_length=80, null=True)),
                ('hasc_1', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'IND_STATES',
                'managed': False,
            },
        ),
    ]
