# Generated by Django 3.1 on 2020-08-27 00:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCenGovt',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('cutdescrip', models.CharField(blank=True, max_length=254, null=True)),
                ('descriptio', models.CharField(blank=True, max_length=254, null=True)),
                ('street', models.CharField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=254, null=True)),
                ('pincode', models.CharField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, max_length=254, null=True)),
                ('gid_1', models.CharField(blank=True, max_length=80, null=True)),
                ('gid_2', models.CharField(blank=True, max_length=80, null=True)),
                ('name_2', models.CharField(blank=True, max_length=80, null=True)),
                ('varname_2', models.CharField(blank=True, max_length=80, null=True)),
                ('hasc_2', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'TEST_CEN_GOVT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestCenPvt',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('cutdescrip', models.CharField(blank=True, max_length=254, null=True)),
                ('descriptio', models.CharField(blank=True, max_length=254, null=True)),
                ('street', models.CharField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=254, null=True)),
                ('pincode', models.CharField(blank=True, max_length=254, null=True)),
                ('state', models.CharField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, max_length=254, null=True)),
                ('gid_1', models.CharField(blank=True, max_length=80, null=True)),
                ('gid_2', models.CharField(blank=True, max_length=80, null=True)),
                ('name_2', models.CharField(blank=True, max_length=80, null=True)),
                ('varname_2', models.CharField(blank=True, max_length=80, null=True)),
                ('hasc_2', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'TEST_CEN_PVT',
                'managed': False,
            },
        ),
    ]
