# Generated by Django 3.1 on 2020-08-28 00:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testcengovt_testcenpvt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCoords',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('gid_1', models.CharField(blank=True, max_length=80, null=True)),
                ('name_1', models.CharField(blank=True, max_length=80, null=True)),
                ('state', models.CharField(blank=True, max_length=80, null=True)),
                ('gid_2', models.CharField(blank=True, max_length=80, null=True)),
                ('name_2', models.CharField(blank=True, max_length=80, null=True)),
                ('district', models.CharField(blank=True, max_length=80, null=True)),
                ('engtype_2', models.CharField(blank=True, max_length=80, null=True)),
                ('statecode', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'DISTRICT_COORDS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateCoords',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('gid_1', models.CharField(blank=True, max_length=80, null=True)),
                ('name_1', models.CharField(blank=True, max_length=80, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('engtype_1', models.CharField(blank=True, max_length=80, null=True)),
                ('statecode', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'STATE_COORDS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestCen',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('catid', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('cutdescription', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('street', models.CharField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=254, null=True)),
                ('zip', models.CharField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.CharField(blank=True, max_length=254, null=True)),
                ('gid_1', models.CharField(blank=True, max_length=80, null=True)),
                ('gid_2', models.CharField(blank=True, max_length=80, null=True)),
                ('name_2', models.CharField(blank=True, max_length=80, null=True)),
                ('district', models.CharField(blank=True, max_length=80, null=True)),
                ('engtype_2', models.CharField(blank=True, max_length=80, null=True)),
                ('statecode', models.CharField(blank=True, max_length=3, null=True)),
                ('name_1', models.CharField(blank=True, max_length=80, null=True)),
                ('state', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'TEST_CEN',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TestCenGovt',
        ),
        migrations.DeleteModel(
            name='TestCenPvt',
        ),
        migrations.AlterModelTable(
            name='inddistricts',
            table='IND_DISTRICTS2',
        ),
        migrations.AlterModelTable(
            name='indstates',
            table='IND_STATES2',
        ),
    ]
